# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

r_packages:
  - covr
before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

matrix:
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'remotes::install_github("rstudio/rmarkdown", upgrade = "never")'
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master

